.TH QTPARTED 1 "February 2011"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
QTParted \- A GUI for Parted
.SH SYNOPSIS
.B qtparted
.SH DESCRIPTION
.B qtparted 
is a GUI for parted resembling (by design) Powerquest Partition Magic.

To use QTParted just start it using root privilege.
.PP
.SH OPTIONS
This program currently has no relevant command line options
.SH AUTHOR
This manual page was written by Vanni Brutto <zanac4ever@virgilio.it>
